title: Your Blog Title
description: "A short description of your blog."
url: "https://vanila.blog.github.io" # Ensure this matches your live domain
baseurl: ""
plugins:
  - jekyll-seo-tag
  - jekyll-feed
